version: '3'
services:
    prerender:
        build: .
        ports:
        - 3000:3000
        environment:
        - MEMORY_CACHE=0
        - CACHE_MAXSIZE=1000
        - CACHE_TTL=6000
        - MAP_DOMAIN_TO_LOCALHOST=example.com,host.docker.internal
        restart: unless-stopped