version: "3"
services:
  prerender:
    build: .
    ports:
      - 3000:3000
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
      - ALLOWED_DOMAINS=example.com,www.example.com
    restart: unless-stopped
